name: Daily VoD check cron job
on:
  schedule:
    - cron: '30 2 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Daily VoD check cron job
        run: |
          curl --request GET \
          --url 'https://beacon-app-5jegr.ondigitalocean.app/api/vod' \
          --header 'Authorization: Bearer ${{ secrets.API_KEY }}'